version: '3'
 
services:
  web:
    container_name: laravel-de-web
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
     - .:/var/www/html:cached
    ports:
     - "8080:80"

  db:
    container_name: laravel-de-mydb
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
    volumes:
      - ./Docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "13306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-de-myadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8880:80
    volumes:
      - ./phpmyadmin/sessions:/sessions